name: supercitoyen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^1.1.1
  flutter:
    sdk: flutter
  camera: ^0.5.8+11
  path_provider: ^1.6.24
  path: ^1.6.4
  esys_flutter_share: ^1.0.2
  image_picker: ^0.6.7+14
  cloud_firestore: ^0.14.3
  firebase_core: ^0.5.2+1
  firebase_auth: 
  flutter_bloc: ^6.1.1
  bloc: ^6.1.0
  geolocator: ^6.1.8
  geocoder: ^0.2.1
  geocoding: ^1.0.5
  latlng: ^0.0.2
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+2
  location: ^2.3.5
  http: ^0.12.2
  uuid: ^2.2.2
  flutter_google_places: ^0.2.6
  google_maps_webservice: ^0.0.18
  pin_code_fields: ^6.0.1
  flare_flutter: ^2.0.6
  intl_phone_number_input: ^0.5.2+2
  dropdown_search: ^0.4.8
  intl: ^0.16.1
  sms_autofill: ^1.2.6
  firebase_storage: ^4.0.1
  back_button_interceptor: ^4.4.0
  intl_translation: ^0.17.10+1
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5
  readmore: ^1.0.0
  share: ^0.6.5+4
  flutter_rating_bar: ^3.2.0+1
  smooth_star_rating: ^1.1.1
  url_launcher: ^5.7.10
  image_cropper: ^1.3.1
  flutter_localizations:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  
  
 

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoBleu.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/LogoBlanc.png
    - assets/images/LogoBleu.png
    - assets/images/Logogrand.png
    - assets/images/Logopetit.png
    - assets/images/incendie.jpg
    - assets/images/inondation.jpg
    - assets/images/inondation2.jpg
    - assets/images/route.png
    - assets/images/trou.jpg
    - assets/images/potoElectrique.jpg
    - assets/images/NetferLogo.png
    - assets/images/notfound 1.png
    - assets/images/notfound 2.png
    - assets/images/notfound 3.png
    - assets/images/notfound 4.png
    - assets/images/notfound 5.jpg
    - assets/images/dechets.jpg
    - assets/images/dechetsAlger.jpg
    - assets/images/trouRoute2.jpg
    - assets/images/trouRoute.jpg
    - assets/images/fuiteEau.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
